import {UnitKey} from './unit';

export enum IngredientKey {
  Flour = 'flour',
  PowderedSugar = 'powdered_sugar',
  Oil = 'oil',
  BakingPowder = 'baking_powder',
  EggYolk = 'egg_yolk',
  Butter = 'butter',
  VanillaPowder = 'vanilla_powder',
  Milk = 'milk',
  Egg = 'egg',
  Sugar = 'sugar',
  StrawberryJelly = 'strawberry_jelly',
  HotWater = 'hot_water',
  ApricotJam = 'apricot_jam',
  Zucchini = 'zucchini',
  PepperPaste = 'pepper_paste',
  TomatoPaste = 'tomato_paste',
  BlackPepper = 'black_pepper',
  RedPepper = 'red_pepper',
  Salt = 'salt',
  GroundBeef = 'ground_beef',
  Onion = 'onion',
  SevenSpices = 'seven_spices',
}

export const IngredientNames: Record<IngredientKey, { en: string; hy: string }> = {
  [IngredientKey.Flour]: { en: 'flour', hy: 'ալիւր' },
  [IngredientKey.PowderedSugar]: { en: 'powdered sugar', hy: 'փոշի շաքար' },
  [IngredientKey.Oil]: { en: 'oil', hy: 'ձէթ' },
  [IngredientKey.BakingPowder]: { en: 'baking powder', hy: 'պէյքինկ փաուտըր' },
  [IngredientKey.EggYolk]: { en: 'egg yolk', hy: 'հաւկիթի դեղնուց' },
  [IngredientKey.Butter]: { en: 'butter', hy: 'կարագ' },
  [IngredientKey.VanillaPowder]: { en: 'vanilla powder', hy: 'փոշի վանիլ' },
  [IngredientKey.Milk]: { en: 'milk', hy: 'կաթ' },
  [IngredientKey.Egg]: { en: 'egg', hy: 'հաւկիթ' },
  [IngredientKey.Sugar]: { en: 'sugar', hy: 'շաքար' },
  [IngredientKey.StrawberryJelly]: { en: 'strawberry jelly', hy: 'ելակի ճելօ' },
  [IngredientKey.HotWater]: { en: 'hot water', hy: 'տաք ջուր' },
  [IngredientKey.ApricotJam]: { en: 'apricot jam', hy: 'ծիրանի անուշ' },
  [IngredientKey.Zucchini]: { en: 'zucchini', hy: 'դդում'},
  [IngredientKey.PepperPaste]: { en: 'pepper paste', hy: 'պղպեղի խիւս' },
  [IngredientKey.TomatoPaste]: { en: 'tomato paste', hy: 'լոլիկի խիւս' },
  [IngredientKey.BlackPepper]: { en: 'black pepper', hy: 'սեւ պղպեղ' },
  [IngredientKey.RedPepper]: { en: 'red pepper', hy: 'կարմիր պղպեղ' },
  [IngredientKey.Salt]: { en: 'salt', hy: 'աղ' },
  [IngredientKey.GroundBeef]: { en: 'ground beef', hy: 'քաշուած միս' },
  [IngredientKey.Onion]: { en: 'onion', hy: 'սոխ' },
  [IngredientKey.SevenSpices]: { en: 'seven spices', hy: 'եօթ համեմներ' },
};
