import {UnitKey} from './unit';

export enum IngredientKey {
  Flour = 'flour',
  PowderedSugar = 'powdered_sugar',
  Oil = 'oil',
  BakingPowder = 'baking_powder',
  EggYolk = 'egg_yolk',
  Butter = 'butter',
  VanillaPowder = 'vanilla_powder',
  Milk = 'milk',
  Egg = 'egg',
  Sugar = 'sugar',
  StrawberryJelly = 'strawberry_jelly',
  HotWater = 'hot_water',
  ApricotJam = 'apricot_jam',
  Zucchini = 'zucchini',
  PepperPaste = 'pepper_paste',
  TomatoPaste = 'tomato_paste',
  BlackPepper = 'black_pepper',
  RedPepper = 'red_pepper',
  Salt = 'salt',
  GroundBeef = 'ground_beef',
  Onion = 'onion',
  SevenSpices = 'seven_spices',
  SrirachaSauce = 'sriracha_sauce',
  SoySauce = 'soy_sauce',
  AppleCiderVinegar = 'apple_cider_vinegar',
  Honey = 'honey',
  Garlic = 'garlic',
  Ginger = 'ginger',
  CornFlour = 'corn_flour',
  PeanutOil = 'peanut_oil',
  SesameOil = 'sesame_oil',
  ChickenBreast = 'chicken_breast',
  JasmineRice = 'jasmine_rice',
  ColdWater = 'cold_water',
  Broccolini = 'broccolini',
  WhitePepper = 'white_pepper',
  CocoaPowder = 'cocoa_powder',
  BakingSoda = 'baking_soda',
  Yogurt = 'yogurt',
  Vanilla = 'vanilla',
  N5Spaghetti = 'n5spaghetti',
  BiftekMeat = 'biftek_meat',
  FineSemolina = 'fine_semolina',
  SunflowerOil = 'sunflower_oil',
  Turmeric = 'turmeric',
  Anise = 'anise',
}

export const IngredientNames: Record<IngredientKey, { en: string; hy: string }> = {
  [IngredientKey.Flour]: {en: 'flour', hy: 'ալիւր'},
  [IngredientKey.PowderedSugar]: {en: 'powdered sugar', hy: 'փոշի շաքար'},
  [IngredientKey.Oil]: {en: 'oil', hy: 'ձէթ'},
  [IngredientKey.BakingPowder]: {en: 'baking powder', hy: 'պէյքինկ փաուտըր'},
  [IngredientKey.EggYolk]: {en: 'egg yolk', hy: 'հաւկիթի դեղնուց'},
  [IngredientKey.Butter]: {en: 'butter', hy: 'կարագ'},
  [IngredientKey.VanillaPowder]: {en: 'vanilla powder', hy: 'փոշի վանիլ'},
  [IngredientKey.Milk]: {en: 'milk', hy: 'կաթ'},
  [IngredientKey.Egg]: {en: 'eggs', hy: 'հաւկիթ'},
  [IngredientKey.Sugar]: {en: 'sugar', hy: 'շաքար'},
  [IngredientKey.StrawberryJelly]: {en: 'strawberry jelly', hy: 'ելակի ճելօ'},
  [IngredientKey.HotWater]: {en: 'hot water', hy: 'տաք ջուր'},
  [IngredientKey.ApricotJam]: {en: 'apricot jam', hy: 'ծիրանի անուշ'},
  [IngredientKey.Zucchini]: {en: 'zucchini', hy: 'դդում'},
  [IngredientKey.PepperPaste]: {en: 'pepper paste', hy: 'պղպեղի խիւս'},
  [IngredientKey.TomatoPaste]: {en: 'tomato paste', hy: 'լոլիկի խիւս'},
  [IngredientKey.BlackPepper]: {en: 'black pepper', hy: 'սեւ պղպեղ'},
  [IngredientKey.RedPepper]: {en: 'red pepper', hy: 'կարմիր պղպեղ'},
  [IngredientKey.Salt]: {en: 'salt', hy: 'աղ'},
  [IngredientKey.GroundBeef]: {en: 'ground beef', hy: 'քաշուած միս'},
  [IngredientKey.Onion]: {en: 'onion', hy: 'սոխ'},
  [IngredientKey.SevenSpices]: {en: 'seven spices', hy: 'եօթ համեմներ'},
  [IngredientKey.SrirachaSauce]: {en: 'sriracha sauce', hy: 'սրիրաչա սոուս'},
  [IngredientKey.SoySauce]: {en: 'soy sauce', hy: 'սոյայի սոուս'},
  [IngredientKey.AppleCiderVinegar]: {en: 'apple cider vinegar', hy: 'խնձորի քացախ'},
  [IngredientKey.Honey]: {en: 'honey', hy: 'մեղր'},
  [IngredientKey.Garlic]: {en: 'garlic', hy: 'սխտոր'},
  [IngredientKey.Ginger]: {en: 'ginger', hy: 'կոճապղպեղ'},
  [IngredientKey.CornFlour]: {en: 'corn flour', hy: 'գետնանուշի ալիւր'},
  [IngredientKey.PeanutOil]: {en: 'peanut oil', hy: 'գետնանուշի ձէթ'},
  [IngredientKey.SesameOil]: {en: 'sesame oil', hy: 'ծովաբոյի ձէթ'},
  [IngredientKey.ChickenBreast]: {en: 'chicken breast', hy: 'հաւի կրծքամիս'},
  [IngredientKey.JasmineRice]: {en: 'jasmine rice', hy: 'ճասմինի բրինձ'},
  [IngredientKey.ColdWater]: {en: 'cold water', hy: 'ցուրտ ջուր'},
  [IngredientKey.Broccolini]: {en: 'broccolini', hy: 'բրոկոլինի'},
  [IngredientKey.WhitePepper]: {en: 'white pepper', hy: 'սպիտակ պղպեղ'},
  [IngredientKey.CocoaPowder]: {en: 'cocoa powder', hy: 'փոշի գագաօ'},
  [IngredientKey.BakingSoda]: {en: 'baking soda', hy: 'պէյքինկ սոտա'},
  [IngredientKey.Yogurt]: {en: 'yogurt', hy: 'մածուն'},
  [IngredientKey.Vanilla]: {en: 'vanilla', hy: 'վանիլ'},
  [IngredientKey.N5Spaghetti]: {en: 'N°5 Spaghetti', hy: 'n5 սպագետի'},
  [IngredientKey.BiftekMeat]: {en: 'biftek meat', hy: 'բիֆթեքի միս'},
  [IngredientKey.FineSemolina]: { en: 'fine semolina', hy: 'բարակ սէմոլինա' },
  [IngredientKey.SunflowerOil]: { en: 'sunflower oil', hy: 'արեւածաղկի ձէթ' },
  [IngredientKey.Turmeric]: { en: 'turmeric', hy: 'կուրկումա' },
  [IngredientKey.Anise]: { en: 'anise', hy: 'անիսոն' },
};
